name: Prod

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install pnpm
        run: |
          curl -L https://github.com/pnpm/pnpm/releases/download/v8.7.5/pnpm-linux-x64 -o pnpm
          chmod +x pnpm
          mkdir -p /usr/local/bin
          sudo mv pnpm /usr/local/bin
          pnpm --version

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install npm dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install --offline

      - name: Build
        run: pnpm build
      
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy built artifacts
        run: rsync -avzr --delete --filter=':- .gitignore' ./* /web
