name: Prod

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.5
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v4

      - name: Deploy builded artifacts
        run: rsync -avzr --delete --filter=':- .gitignore' dist/* /web